<template>
  <ion-page>
    <ion-content :fullscreen="true">
      <div style="margin-top: 175px;width: 70%;margin-left: auto;margin-right: auto;">
        <ion-img src="/assets/img/logo.png"></ion-img>
      </div>
      <div style="width: 50px;margin: 75px auto;" >
        <div class="loadingio-spinner-blocks-8vnjff9yvw4"><div class="ldio-2uob2b5nc8w">
        <div style='left:25.5px;top:25.5px;animation-delay:0s'></div><div style='left:42.5px;top:25.5px;animation-delay:0.07668711656441718s'></div><div style='left:59.5px;top:25.5px;animation-delay:0.15337423312883436s'></div><div style='left:25.5px;top:42.5px;animation-delay:0.5368098159509203s'></div><div style='left:59.5px;top:42.5px;animation-delay:0.2300613496932515s'></div><div style='left:25.5px;top:59.5px;animation-delay:0.460122699386503s'></div><div style='left:42.5px;top:59.5px;animation-delay:0.38343558282208584s'></div><div style='left:59.5px;top:59.5px;animation-delay:0.3067484662576687s'></div>
        </div></div>
      </div>
    </ion-content>
  </ion-page>
</template>

<script>
import { IonPage, IonContent, IonImg } from '@ionic/vue'
import { useRouter } from 'vue-router'
import { mapActions } from 'vuex';

export default {
  components: {
    IonPage,
    IonContent,
    IonImg
  },
  setup(){
    const router = useRouter();

    return {
      router
    }
  },
  created(){
    setTimeout(() => {
      // if( this.hasSchoolId() )
      //   this.router.push('/escola')
      // else 
        this.isSigned().then((res) => {
            if(res) this.router.push('/home')
            else this.router.push('/login')
        })      
    }, 1000)
  },
  methods: {
    ...mapActions("auth", ["isSigned"]),
    ...mapActions("auth", ["hasSchoolId"]),
  }
}
</script>

<style type="text/css">
@keyframes ldio-2uob2b5nc8w {
  0% { background: #536d3e }
  12.5% { background: #536d3e }
  12.625% { background: #93c272 }
  100% { background: #93c272 }
}
.ldio-2uob2b5nc8w div {
  position: absolute;
  width: 15px;
  height: 15px;
  background: #93c272;
  animation: ldio-2uob2b5nc8w 0.6134969325153374s linear infinite;
}
.loadingio-spinner-blocks-8vnjff9yvw4 {
  width: 50px;
  height: 50px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-2uob2b5nc8w {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.5);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-2uob2b5nc8w div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>